services:
  postgres:
    image: postgres:16
    container_name: postgret-golang
    restart: always
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=huuloc2026
      - POSTGRES_DB=8663-microservices
    volumes:
      - social_postgres:/var/lib/postgresql/data
    networks:
      - social
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      timeout: 20s
      retries: 10

networks:
  social:

volumes:
  social_postgres:
